behaviors:
  ThunderSearch:
    trainer_type: ppo
    time_horizon: 256 # Enyhén növelve a hosszabb távú tervezésért
    max_steps: 3e6
    hyperparameters:
      learning_rate: 1e-4
      batch_size: 2048
      buffer_size: 50000
      num_epoch: 3
    network_settings:
      normalize: true
      num_layers: 3
      hidden_units: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.1 # Megnövelt súly a kíváncsiságnak a jobb felfedezésért
        learning_rate: 0.0003
        encoding_size: 128
    summary_freq: 50000
    threaded: true
torch_settings:
  device: cpu